name: Docker Build and Push

on:
  push:
    branches: [ "master"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%Y%m%d)"

      - name: Get short commit hash
        id: commit_hash
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

      - name: Build and Push Docker Image
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin  
          docker build -t aj1009/gitactionapi:${{ steps.date.outputs.date }}-${{ steps.commit_hash.outputs.commit_hash }} .
          docker push aj1009/gitactionapi:${{ steps.date.outputs.date }}-${{ steps.commit_hash.outputs.commit_hash }}
      